// <auto-generated />
using System;
using ManageMoney.Infraestrucutre.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManageMoney.Infraestrucutre.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241026142534_RefactoArtefactLogic")]
    partial class RefactoArtefactLogic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManageMoney.Domain.Entities.AccountCash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountCash", (string)null);
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.Consumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Consumption", (string)null);
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.FinancialObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FinancialObjectives", (string)null);
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.Investiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Investments", (string)null);
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountCashId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountCashId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("FinancialObjectiveId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountCashId1");

                    b.HasIndex("FinancialObjectiveId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.AccountCash", b =>
                {
                    b.HasOne("ManageMoney.Domain.Entities.User", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.Consumption", b =>
                {
                    b.HasOne("ManageMoney.Domain.Entities.User", null)
                        .WithMany("Consumptions")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.Investiment", b =>
                {
                    b.HasOne("ManageMoney.Domain.Entities.User", null)
                        .WithMany("Investiments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.User", b =>
                {
                    b.HasOne("ManageMoney.Domain.Entities.AccountCash", "AccountCash")
                        .WithMany()
                        .HasForeignKey("AccountCashId1");

                    b.HasOne("ManageMoney.Domain.Entities.FinancialObjective", "FinancialObjective")
                        .WithMany()
                        .HasForeignKey("FinancialObjectiveId");

                    b.Navigation("AccountCash");

                    b.Navigation("FinancialObjective");
                });

            modelBuilder.Entity("ManageMoney.Domain.Entities.User", b =>
                {
                    b.Navigation("Consumptions");

                    b.Navigation("Investiments");
                });
#pragma warning restore 612, 618
        }
    }
}
